sonar.verbose=true
sonar.projectKey=org.opensbpm.opensbpm:frontend

# We don't need to exclude it in sonar.sources because it is automatically taken care of
sonar.test.inclusions=src/**/*.spec.js,src/**/*.spec.jsx,src/**/*.test.js,src/**/*.test.jsx,\
                    src/**/*.spec.ts,src/**/*.spec.tsx,src/**/*.test.ts,src/**/*.test.tsx
#TODO sonar.testExecutionReportPaths=test-results/jest.xml
sonar.javascript.lcov.reportPaths=coverage/lcov.info
