<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.opensbpm</groupId>
    <artifactId>opensbpm</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>OpenSBPM Application</name>
    <description>OpenSBPM Application</description>
    <url>http://opensbpm.org</url>
    <organization>
        <name>OpenSBPM</name>
        <url>http://opensbpm.org</url>
    </organization>

    <developers>
        <developer>
            <name>Stefan Sedelmaier</name>
            <email>stefan@sedelmaier.at</email>
        </developer>
    </developers>

    <modules>
        <module>engine</module>
        <module>vaadinui</module>
    </modules>

    <scm>
        <connection>scm:git:git@github.com:opensbpm/opensbpm.git</connection>
        <developerConnection>scm:git:git@github.com:opensbpm/opensbpm.git</developerConnection>
        <url>https://github.com/opensbpm/opensbpm</url>
    </scm>
    <distributionManagement>
        <snapshotRepository>
            <id>opensbpm-snapshots</id>
            <url>https://team.sedelmaier.at/archiva/repository/opensbpm-snapshots/</url>
        </snapshotRepository>
    </distributionManagement>

    <properties>
        <java.version>17</java.version>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>


        <surefire.reportsDirectory>${project.build.directory}/surefire-reports</surefire.reportsDirectory>
        <failsafe.reportsDirectory>${project.build.directory}/failsafe-reports</failsafe.reportsDirectory>

        <jacoco.surefire.destFile>${project.build.directory}/jacoco.exec</jacoco.surefire.destFile>
        <jacoco.failsafe.destFile>${project.build.directory}/jacoco-it.exec</jacoco.failsafe.destFile>

        <!-- surefire + failsafe -->
        <sonar.junit.reportPaths>
            ${project.build.directory}/surefire-reports,
            ${project.build.directory}/failsafe-reports
        </sonar.junit.reportPaths>
        <sonar.coverage.jacoco.xmlReportPaths>
            ${project.build.directory}/site/jacoco/jacoco.xml,${project.build.directory}/site/jacoco-it/jacoco.xml
        </sonar.coverage.jacoco.xmlReportPaths>

        <!-- dependency versions -->
        <opensbpm.version>1.1-SNAPSHOT</opensbpm.version>
        <spring.boot.version>3.4.1</spring.boot.version>
        <apache.cxf.version>4.0.4</apache.cxf.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <!--
            ===================
            Import Dependencies
            ===================
            -->
            <dependency>
                <groupId>org.opensbpm.engine</groupId>
                <artifactId>engine-bom</artifactId>
                <version>${opensbpm.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring.boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.cxf</groupId>
                <artifactId>apache-cxf</artifactId>
                <version>${apache.cxf.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <repositories>
        <!-- The order of definitions matters. Explicitly defining central here to make sure it has the highest priority. -->

        <!-- Main Maven repository -->
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>

        <repository>
            <id>opensbpm-snapshots</id>
            <name>OpenSBPM Snapshots</name>
            <url>http://team.sedelmaier.at/archiva/repository/opensbpm-snapshots/</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.11.0</version>
                </plugin>
                <plugin>
                    <groupId>org.jacoco</groupId>
                    <artifactId>jacoco-maven-plugin</artifactId>
                    <version>0.8.11</version>
                </plugin>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.2.2</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-failsafe-plugin</artifactId>
                    <version>3.1.2</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-pmd-plugin</artifactId>
                    <version>3.17.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>

                <plugin>
                    <groupId>org.sonarsource.scanner.maven</groupId>
                    <artifactId>sonar-maven-plugin</artifactId>
                    <version>3.7.0.1746</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <showDeprecation>true</showDeprecation>
                    <compilerArgs>
                        <!--arg>-verbose</arg-->
                        <!-- see "javac -help -X" for help -->
                        <!--
                        <arg>-Xlint:all,-serial</arg>
                        -->
                    </compilerArgs>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-prepare-agent-integration</id>
                        <goals>
                            <goal>prepare-agent-integration</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-report</id>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>default-report-integration</id>
                        <goals>
                            <goal>report-integration</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-failsafe-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <!-- not needed for now
                    <useManifestOnlyJar>false</useManifestOnlyJar>
                    -->
                    <reportsDirectory>${failsafe.reportsDirectory}</reportsDirectory>
                    <summaryFile>${failsafe.reportsDirectory}/failsafe-summary.xml</summaryFile>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
