apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-client
spec:
  #ttlSecondsAfterFinished: 100 #in Seconds
  template:
    spec:
      containers:
        - name: opensbpm-e2e-client
          image: opensbpm/e2e-client
          args: [
            "--e2e.execution=single",
            "--url=https://cloud-dev.opensbpm.org",
            "--nodes=1",
            "--pods=1",
            "--processes=640"
          ]
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "4"
              memory: "512Mi"
              #memory: "768Mi"
              #memory: "1024Mi"

          #see https://docs.spring.io/spring-boot/reference/features/external-config.html#features.external-config.files
          volumeMounts:
            - name: e2e-client-volume
              mountPath: /workspace/config/application.yaml
              subPath: application.yaml
      volumes:
        - name: e2e-client-volume
          configMap:
            name: e2e-client
      restartPolicy: Never

  backoffLimit: 1
