apiVersion: batch/v1
kind: Job
metadata:
  name: e2e-client
spec:
  #ttlSecondsAfterFinished: 100 #in Seconds
  template:
    spec:
      containers:
        - name: opensbpm-e2e-client
          image: sedstef/opensbpm-e2e
          args: ["--url",  "https://cloud-dev.opensbpm.org" ,"--processes", "10"]
          volumeMounts:
            - name: e2e-client-storage
              mountPath: /var/run/e2e-client
      volumes:
        - name: e2e-client-storage
          persistentVolumeClaim:
            claimName: e2e-client-pv-claim
      restartPolicy: Never
  backoffLimit: 1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: e2e-client-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
