apiVersion: v1
kind: ConfigMap
metadata:
  name: engine-config
data:
  application.yaml: |
    #debug: true
    
    #spring.datasource.hikari.pool-name=MyHikariPool
    #spring.datasource.hikari.connection-timeout: 50000
    #spring.datasource.hikari.metrics-tracking: true
    #spring.datasource.hikari.leak-detection-threshold: 2000

    #spring.jpa.show-sql: true
    #spring.jpa.properties.hibernate.format_sql: true
    #spring.jpa.properties.hibernate.generate_statistics: true
    
    spring.jpa.properties.hibernate.session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 500
    logging.level.org.hibernate.SQL_SLOW: INFO
    
    #logging.level.org.springframework.transaction.interceptor: TRACE
    #logging.level:
    #  org.springframework.security.oauth2: DEBUG
    #  org.apache.cxf: DEBUG
