apiVersion: v1
kind: Service
metadata:
  name: engine
  labels:
    app: engine
spec:
  type: LoadBalancer
  selector:
    app: engine
  ports:
    - name: engine-http
      port: 8090
      targetPort: engine-http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: engine
  labels:
    app: engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
      annotations:
        # Prometheus configuration
        prometheus.io/scrape: "true"
        prometheus.io/path: "/api/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: engine
          image: opensbpm/engine:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://engine-db:5432/opensbpm
            - name: SPRING_DATASOURCE_USERNAME
              value: opensbpm
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: opensbpm-secrets
                  key: engine-db-password
            - name: SPRING_JPA_HIBERNATE_DDLAUTO
              value: update
          resources:
#            requests:
#              memory: "512Mi"
#            limits:
              memory: "768Mi"
#              memory: "1024Mi"
          ports:
            - name: engine-http
              containerPort: 8090
          livenessProbe:
            httpGet:
              port: 8090
              path: /api/actuator/health/liveness
            initialDelaySeconds: 3
            #periodSeconds: 2
          readinessProbe:
            httpGet:
              port: 8090
              path: /api/actuator/health/readiness
            initialDelaySeconds: 35
          volumeMounts:
            - name: engine-config-volume
              mountPath: /workspace/config/application.yaml
              subPath: application.yaml
      volumes:
        - name: engine-config-volume
          configMap:
            name: engine-config
      restartPolicy: Always
