apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opensbpm
resources:
  - namespace.yaml
  - lets-encrypt.yaml
  - ingress.yaml
  - pv-keycloak-db-local.yaml
  - keycloak-db.yaml
  - keycloak.yaml
  - pv-engine-db-local.yaml
  - engine-db.yaml
  - engine.yaml
  - frontend.yaml
  - vaadinui.yaml
