apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-db
  labels:
    app: keycloak-db
spec:
  capacity:
    storage: 2Gi
  accessModes: [ ReadWriteOnce ]
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/opensbpm/volumes/keycloak-database
