---
- include: microk8s_token.yml

#- name: Configure the controller server
#  become: yes
#  tasks:
- name: Install python3-kubernetes
  ansible.builtin.apt:
    name: python3-kubernetes
    update_cache: true
    state: present

- name: Create kubctl config
  ansible.builtin.shell:
    cmd: |
      mkdir -p ~/.kube
      microk8s config > ~/.kube/config
      sed -i 's/microk8s/opensbpm/' ~/.kube/config
    creates: ~/.kube/config

- name: Fetch the kubectl config from the remote server
  ansible.builtin.fetch:
    src: /root/.kube/config
    #dest: ~/.kube/opensbpm@hetzner
    dest: /mnt/c/Users/stefan/.kube/opensbpm@hetzner.yaml
    flat: yes

- name: Create opensbpm directory
  ansible.builtin.file:
    path: /srv/opensbpm
    state: directory

- name: Copy observability values
  ansible.builtin.copy:
    src: observability/values.yaml
    dest: /srv/opensbpm/observability-values.yaml

- name: Activate microk8s plugins
  become: yes
  shell: |
    microk8s enable dns 
    microk8s enable ingress 
    microk8s enable cert-manager 
    microk8s enable observability --kube-prometheus-stack-values=/srv/opensbpm/observability-values.yaml

  #https://github.com/canonical/microk8s-core-addons/blob/main/addons/observability/enable

- include: kubernetes.yml
