---
- name: Copy stresstest script
  ansible.builtin.copy:
    src: stresstest.sh
    dest: //usr/local/bin/stresstest.sh
    mode: "0777"

- name: Pull the userbot image
  ansible.builtin.shell: docker pull docker.io/opensbpm/userbot
