---
# This playbook creates a microk8s cluster with Hetzner cloud servers

- import_playbook: infrastructure/hcluster.yml
- import_playbook: infrastructure/stresstest.yml

- name: Apply configuration to control planes
  hosts: control_planes

  roles:
    - microk8s
    - controlplane
    - litmuschaos


- name: Apply configuration to worker node
  hosts: worker_nodes

  roles:
    - microk8s
    - worker


- name: Apply configuration to stresstest server
  hosts: stresstest

  roles:
    - podman
    - stresstest
    - chaostest


- name: Apply opensbpm k8s config
  hosts: localhost

  roles:
    - opensbpm
