---
- name: Setup Hetzner cluster
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create the IPv4 Primary IP
      hetzner.hcloud.primary_ip:
        name: opensbpm-primary-ip
        datacenter: fsn1-dc14
        type: ipv4
        delete_protection: true
        state: present

    - name: Setup controller server
      hetzner.hcloud.server:
        location: fsn1
        name: controller
        server_type: cx22
        image: ubuntu-24.04
        ipv4: opensbpm-primary-ip
        ssh_keys:
          - opensbpm@hetzner
        state: started
      register: controller_info

    - name: Show server details
      debug:
        var: controller_info

    - name: Retrieve ssh key from controller server
      shell: "ssh-keyscan -H -T 120 {{ controller_info.hcloud_server.ipv4_address }}"
      register: controller_sshkeyscan

    - name: Add controller host keys to known_hosts
      ansible.builtin.known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ controller_info.hcloud_server.ipv4_address }}"
        key: "{{ controller_sshkeyscan.stdout }}"
        state: present

    - name: Add controller to inventory
      add_host:
        name: "{{ controller_info.hcloud_server.ipv4_address }}"
        groups: microk8s_controller
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/opensbpm-hetzner

- name: Configure the controller server
  hosts: microk8s_controller
  become: yes
  tasks:
    - name: Install python3-kubernetes
      ansible.builtin.apt:
        name: python3-kubernetes
        update_cache: true
        state: present

    - name: Install basic microk8s
      community.general.snap:
        classic: true
        name:
          - microk8s
        state: present

    - name: Create kubctl config
      ansible.builtin.shell:
        cmd: |
          mkdir -p ~/.kube
          microk8s config > ~/.kube/config
          sed -i 's/microk8s/opensbpm/' ~/.kube/config
        creates: ~/.kube/config

    - name: Fetch the kubectl config from the remote server
      ansible.builtin.fetch:
        src: /root/.kube/config
        #dest: ~/.kube/opensbm@hetzner
        dest: /mnt/c/Users/stefan/.kube/opensbm@hetzner
        flat: yes

    - name: Activate microk8s plugins
      ansible.builtin.command: microk8s enable dns ingress cert-manager dashboard

    - name: Create OpenSBPM namespace in k8s
      kubernetes.core.k8s:
        name: opensbpm
        api_version: v1
        kind: Namespace
        state: present

